import our1 from "../assets/img/products1.png";
import our2 from "../assets/img/product4.png";
import our3 from "../assets/img/product5.png";
import our4 from "../assets/img/our4.png";
import our from "../assets/img/our.png";
import our6 from "../assets/img/our6.png";

export const OurData = [
  {
    nameTitle: "top",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our1,
  },
  {
    nameTitle: "top",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our6,
  },
  {
    nameTitle: "top",
    name: "Eto V Neck Yellow",
    price: "Rp. 129.000",
    image: our1,
  },
  {
    nameTitle: "bottom",
    name: "Macaroon Dry Half",
    price: "Rp. 139.000",
    image: our2,
  },
  {
    nameTitle: "dress",
    name: "Wave Stripe Hally",
    price: "Rp. 130.000",
    image: our3,
  },
  {
    nameTitle: "set",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "knit",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "outer",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "top",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "bottom",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "dress",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "set",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "knit",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "outer",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "top",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "bottom",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "dress",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "set",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "knit",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "outer",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "outer",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "outer",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "knit",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "knit",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "knit",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "top",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "top",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "bottom",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "knit",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "set",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "set",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "set",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "dress",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "dress",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "outer",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "outer",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "outer",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "knit",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "bottom",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "dress",
    name: "Floral Waffle Tee",
    price: "Rp. 119.000",
    image: our,
  },
  {
    nameTitle: "knit",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "dress",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
  {
    nameTitle: "outer",
    name: "Snap Pure Blouse",
    price: "Rp. 225.000",
    image: our6,
  },
  {
    nameTitle: "bottom",
    name: "Eve Punching Floral",
    price: "Rp. 229.000",
    image: our4,
  },
];
